### ISSUE TITLE
conditionally apply custom.rules

### ISSUE THREAD

**Issue by benformosa** [robertdebock/ansible-role-auditd#1]
**Is your feature request related to a problem? Please describe.**
I am planning to apply audit rules using a combination of the OS defaults (`/etc/audit/rules.d/audit.rules`) and a separate role (https://github.com/MindPointGroup/RHEL7-CIS).
I want to use this role to configure auditd, but I don't want it to install any rules.

**Describe the solution you'd like**
A new boolean variable (`auditd_manage_rules`?) which would be used as a condition for running the `place custom.rules` task.

https://github.com/robertdebock/ansible-role-auditd/blob/master/tasks/main.yml:
```yaml
- name: place custom.rules
  template:
    src: custom.rules.j2
    dest: "{{ auditd_config_directory }}/rules.d/custom.rules"
  notify:
    - run augenrules
  when:
    - auditd_manage_rules
```

https://github.com/robertdebock/ansible-role-auditd/blob/master/defaults/main.yml
```yaml
auditd_manage_rules: true
```

**Describe alternatives you've considered**
I could use a separate role to remove (`/etc/audit/rules.d/audit.rules`) and use this role's variables to apply that configuration in `custom.rules`. This would require another role, plus `audit.rules` may get restored during an OS update.

Thank you for your excellent work in producing your Ansible roles!
