### ISSUE TITLE
Auditd.conf contains deprecated options

### ISSUE THREAD

**Issue by stejoo** [robertdebock/ansible-role-auditd#17]
## Describe the bug

The template for `auditd.conf` contains deprecated settings (for auditd 3.0 on RHEL 8[.7]).

## Playbook

```yaml
---
- name: redhat8
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    auditd_manage_rules: false
    auditd_log_format: ENRICHED
    auditd_space_left: 100 
    auditd_space_left_action: syslog
    auditd_admin_space_left: 50
    auditd_admin_space_left_action: rotate
    auditd_disk_full_action: suspend
    auditd_disk_error_action: suspend

  roles:
    - role: robertdebock.auditd
```

## Output

When running something concering auditd, such as `ausearch` you get output stating the configuraton file contains deprecated options:

```
$ sudo ausearch -m avc
The disp_qos option is deprecated - line 15
The dispatcher option is deprecated - line 16
```
Not a showstopper, but should be avoidable.

These options have been deprecated as of auditd-3.0.
I checked the `meta/main.yml` file for distributions supported by this role. This issue matters to them because they ship with auditd 3.0 or up):
- Debian stable (bullseye)
- Fedora 35 (and up)
- openSUSE Tumbleweed
- Red Hat Enterprise Linux 8 (and derivatives)

Other supported distributions that ship an older version, such as auditd 2.8:
- openSUSE Leap 15.4
- Ubuntu 18.04

## Environment

- Control node OS: Fedora 35
- Control node Ansible version: 2.13.4 (in Python venv)
- Managed node OS: EL 8 (Red Hat Enterprise Linux 8.7)

## Suggestion

The role could check the audit version. If it's 3.0 the options can be left out. The settings in question have been deprecated because their functionality has been built into audit itself per 3.0 [1].

If I find time I will try to submit a PR for this issue.

[1]: https://access.redhat.com/solutions/6053441
