### ISSUE TITLE
auditd is not restarted properly

### ISSUE THREAD

**Issue by stejoo** [robertdebock/ansible-role-auditd#18]
## Describe the bug

The handler that is supposed to restart `auditd` does not work. The `auditd` service is not restarted.

We added `auditd_log_group: splunk` setting and ran the playbook to implement the configuration change. The role ran without problems. Including the run of the handler at the end (`restart auditd`) which returns a `changed` status, as expected. However, the configuration change did not take effect. The log file was still owned by `root:root`. Looking at the service status showed the `auditd` daemon was not restarted.

## Playbook

```yaml
- hosts: all
  become: true
  vars:
    auditd_manage_rules: false
    auditd_log_format: ENRICHED
    auditd_space_left: 100
    auditd_space_left_action: syslog
    auditd_admin_space_left: 50
    auditd_admin_space_left_action: rotate
    auditd_disk_full_action: suspend
    auditd_disk_error_action: suspend
    auditd_log_group: splunk

  roles:
    - role: robertdebock.auditd
      tags: ['audit', 'auditd']
```

## Output

Relevant output of the playbook run:
```
...
 _______________________________________________ 
< TASK [robertdebock.auditd : configure auditd] >
 ----------------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

Tuesday 10 January 2023  08:09:13 +0100 (0:00:03.114)       0:00:14.201 ******* 
--- before: /etc/audit/auditd.conf
+++ after: /home/stefan/.ansible/tmp/ansible-local-7906_k3_yaj9/tmpw0q9f6us/auditd.conf.j2
@@ -5,7 +5,7 @@
 local_events = yes
 write_logs = yes
 log_file = /var/log/audit/audit.log
-log_group = root
+log_group = splunk
 log_format = ENRICHED
 flush = incremental_async
 freq = 50

changed: [sibvsurheltest.blueforce.intern] => changed=true 

...inbetween tasks ran OK...
 ________________________________________________________ 
< RUNNING HANDLER [robertdebock.auditd : restart auditd] >
 -------------------------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

Tuesday 10 January 2023  08:09:16 +0100 (0:00:00.781)       0:00:17.309 ******* 
changed: [sibvsurheltest.blueforce.intern] => changed=true 
  name: auditd
  state: started
```

However, the file on the system was still owned by the (default) `root` user:
```
# ls -lh /var/log/audit/ 
total 12M
-rw-------.  1 root root 3,3M Jan 10 08:08 audit.log
-r--------.  1 root root 8,1M Jan  6 21:38 audit.log.1
```

Further inquiry showed the `auditd` daemon was not restarted on the system. Performing the restart manually, using the `service` command instead of `systemctl` (as specified by https://access.redhat.com/solutions/2664811), resulting in the expected change to the log file's group ownership:

```
# service auditd restart
Stopping logging:
Redirecting start to /bin/systemctl start auditd.service
# ls -lh /var/log/audit/
total 12M
-rw-r-----.  1 root splunk 3,4M Jan 10 08:11 audit.log
-r--r-----.  1 root root   8,1M Jan  6 21:38 audit.log.1
```

The role does not restart the `auditd` daemon properly.

## Debugging the issue

The role's `restart auditd` handler (at tag `3.2.4`) looks like this:
```
- name: restart auditd
  ansible.builtin.service:
    name: "{{ auditd_service }}"
    state: restarted
    use: service  # systemctl can't restart auditd, service can: https://access.redhat.com/solutions/2664811
  when:
    - not ansible_check_mode | bool
```

The `use` argument does not seem to have the desired effect. My theory at this point was Ansible still calling `systemctl restart auditd`, which is incorrect for this service. It demands to be restarted with `service auditd restart`. To test this theory I performed the following on my control node:

```
ANSIBLE_KEEP_REMOTE_FILES=1 ansible <myhost> -b -m ansible.builtin.service -a 'name=auditd state=restarted use=service'
```

After "exploding" the resulting AnsiballZ file on the node I had a look at the module code. To test my theory I added some debug code to the resulting `debug_dir/ansible/modules/service.py` module to have it display the commands it executed. This resulted in:

```
[root@myhost ansible-tmp-1673336562.8091812-11481-93647040079523]# /usr/libexec/platform-python AnsiballZ_service.py execute 
Platform: Linux
Distribution: None
Params: {'name': 'auditd', 'state': 'restarted', 'runlevel': 'default', 'arguments': '', 'sleep': None, 'pattern': None, 'enabled': None}
Service: <__main__.LinuxService object at 0x7f6de09dc0f0>
Service command (svc_cmd): /bin/systemctl
Perform execute_command (cmd): /bin/systemctl show 'auditd'
Perform execute_command (cmd): /bin/systemctl stop auditd 
Perform execute_command (cmd): /bin/systemctl start auditd 

{"name": "auditd", "state": "started", "changed": true, "invocation": {"module_args": {"name": "auditd", "state": "restarted", "runlevel": "default", "arguments": "", "sleep": null, "pattern": null, "enabled": null}}}
```

The handler calling `use:` influences the Ansible module chosen by Ansible. It has an effect as Ansible copies over the `ansible.legacy.service` module instead of `ansible.builtin.systemd`. But the `ansible.legacy.service` performs it's own discovery of the init system on the node and chooses `systemctl` if it finds it.

Ansible bug report [22171](https://github.com/ansible/ansible/issues/22171) describes this issue. A [comment](https://github.com/ansible/ansible/issues/22171#issuecomment-328233472) there recommends calling `service` directly with the `command` module:

```
- command: /sbin/service auditd restart
```

Perhaps the role should do exactly that. I'll make a PR shortly.

I am surprised to have hit this bug. Does the `use: service` have the desired effect on other systems or other (older?) Ansible versions? Was this just never noticed (which I would find very surprising)?

## Environment

- Control node OS: Fedora 36
- Control node Ansible version: 2.13.6
- Managed node OS: RHEL 8.7
