### ISSUE TITLE
Support custom rules which use neither the -w nor -S flags

### ISSUE THREAD

**Issue by mkbajzek** [robertdebock/ansible-role-auditd#5]
## Proposed feature

As documented in [several open-scap rules](https://static.open-scap.org/ssg-guides/ssg-rhel7-guide-standard.html#xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands), best practices call for some `auditd` rules that specify privileged commands' paths using the `-F path=<path>` syntax rather than the `-S` flag. Because the current version of this role only supports entries in `auditd_rules` with a `syscall` field (for which `-S` is used) and entries with a `file` field (for which `-w` is used), it is currently impossible to add entries like `-a always,exit -F path=SETUID_PROG_PATH -F perm=x -F auid>=1000 -F auid!=unset -F key=special-config-changes`, as called for by the open-scap link above.

## Rationale

As documented by [open-scap](https://static.open-scap.org/ssg-guides/ssg-rhel7-guide-standard.html#xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands), "At a minimum, the audit system should collect the execution of privileged commands for all users and root.", and their recommendations include adding rules for specific commands' paths.

**Comment by robertdebock** [comment]
I think this is possible currently. For example your line: `-a always,exit -F path=SETUID_PROG_PATH -F perm=x -F auid>=1000 -F auid!=unset -F key=special-config-changes` would require this variable:

```yaml
auditd_rules:
  - file: SETUID_PROG_PATH
    action: always
    filter: exit
    permissions: execute
    filters:
      - auid>=1000
      - auid!=unset
    keyname: special-config-changes
```

Hope that helps!

**Comment by isuftin** [comment]
I don't think this works.

I want to write out this line: `-a always,exit -F path=/bin/ping -F perm=x -F auid>=500 -F auid!=4294967295 -k privileged`

Here's my line item:
```yaml
      - action: always
        filter: exit
        filters:
          - path=/bin/ping
          - perm=x
          - auid>=500
          - auid!=4294967295
        keyname: privileged
```

This just ends up never getting written out because each item under `auditd_rules` requires either a key named `syscall` or a key named `file`. Otherwise this just gets skipped.

https://github.com/robertdebock/ansible-role-auditd/blob/master/templates/custom.rules.j2#L16

https://github.com/robertdebock/ansible-role-auditd/blob/master/templates/custom.rules.j2#L19

**Comment by robertdebock** [comment]
You are correct.

I've changed 2 things:

1. (not related to your issue, but close) filters were not been implemented for `file` items. I've modified the template a bit.
2. Items with an `action` and no `syscall` or `file` are now looped over.

Now this YAML:

```yaml
        - action: always
          filter: exit
          filters:
            - path=/bin/ping
            - perm=x
            - auid>=500
            - auid!=4294967295
          keyname: privileged
```

Results in your line:

```
-a always,exit -F path=/bin/ping -F perm=x -F auid>=500 -F auid!=4294967295 -k privileged
```

I'll reopen the issue for your feedback and a new release of the role.
